Repository gyrovorbis/sh4zam, pull requests merged in 2025-09, with the labels that each got.

#11 Axis angle and Quat matrix fixes
  include/sh4zam/shz_matrix.h
  include/sh4zam/shz_quat.h
Labels: bug

#13 Change constraints on load_4x4_apply_store
  include/sh4zam/shz_xmtrx.h
Labels: bug

#17 Add distance_sqr and modify signature for template parameter deduction
  include/sh4zam/shz_vector.hpp
Labels: bug, enhancement

#18 Shiny happy 'sembly cleanup.
  include/sh4zam/shz_vector.hpp
  include/sh4zam/shz_xmtrx.h
  include/sh4zam/shz_xmtrx.inl
Labels: enhancement
